# Generated by Django 6.0.4 on 2026-04-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0002_alter_restaurant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField()),
                ('food_description', models.TextField()),
                ('food_image', models.ImageField(upload_to='food_image')),
                ('food_price', models.IntegerField()),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='food_delivery_app.restaurant')),
            ],
        ),
    ]
