# Generated by Django 6.0.4 on 2026-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0003_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_items',
            old_name='restaurent',
            new_name='restaurant',
        ),
    ]
