# Generated by Django 6.0.4 on 2026-04-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0004_rename_restaurent_food_items_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='restaurants'),
        ),
    ]
