# Generated by Django 6.0.3 on 2026-04-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0005_alter_restaurant_category_alter_restaurant_name'),
        ('food_delivery_app', '0005_alter_restaurant_image'),
    ]

    operations = [
    ]
