# Generated by Django 6.0.4 on 2026-04-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
    ]
