# Generated by Django 6.0.4 on 2026-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
