# Generated by Django 6.0.3 on 2026-04-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
