# Generated by Django 6.0.3 on 2026-04-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0009_alter_food_items_food_name'),
        ('food_delivery_app', '0009_order_payment_method_alter_food_items_food_name'),
    ]

    operations = [
    ]
